apiVersion: v1
kind: Namespace
metadata:
  name: database

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: database-rc
  namespace: database
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 8Gi
    limits.cpu: "2"
    limits.memory: 12Gi

---

apiVersion: v1
kind: Namespace
metadata:
  name: admin

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: admin-rc
  namespace: admin
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 8Gi
    limits.cpu: "2"
    limits.memory: 12Gi

---

apiVersion: v1
kind: Namespace
metadata:
  name: user

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-rc
  namespace: user
spec:
  hard:
    requests.cpu: "1.5"
    requests.memory: 10Gi
    limits.cpu: "2.5"
    limits.memory: 14Gi
